config/routes.rb
GoogleMapsAndre::Application.routes.draw do
  resources :users
  get "map/loc"
  get "map/index"
  resources :posts
root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+z/i

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  validates(:name , :presence => true,
                    :lenght =>{
                            :maximum => 50
                    }
          )

  validates(:email , :presence => true,
            :uniqueness =>{
                :case_sensitive => false
            },
            :format =>{
                :with => email_regex
            }


  )

  validates(:password , :presence => true,
            :confirmation => true


  )
  before_save :encrypt_password

  #def has_password(submitted password)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :encryptedpassword, :salt, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user , option = {:size => 60})
      gravatar_image_tag(user.email.downcase , :alt => h(user.name),
                                                :class => 'gravatar',
                                                :gravatar => options
      )
  end



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <title>GoogleMapsAndre</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


  <link rel="stylesheet" href ="http://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.css" />
  <%= javascript_include_tag :defaults %>

  <script src ="http://code.jquery.com/jquery-1.8.2.min.js"></script>
  <script src ="http://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.js" ></script>



</head>
<body>

<div data-role="page">
  <%= yield %>
</div>

</body>
</html>

app/views/map/index.html.erb
<html>
<head>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
  <title>Google Maps API v3: Directions</title>
  <style type="text/css">
      html, body { margin:0; padding:0; width:100%; height:100%; }
      body { background:#FFFFFF; color:#000000; font-family:Arial, Helvetica, sans-serif; font-size:12px; line-height:150%; text-align:center;}
      #map { width:100%; height:95%; }
      input { width:250px; }
  </style>
  <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDIAWj6dRK3iiTYm4q23Vbe-Ina6hSQfd0&sensor=false&language=it" type="text/javascript"></script>
  <script type="text/javascript">
      var directionDisplay;
      var directionsService = new google.maps.DirectionsService();
      var map;

      function initialize() {

         calcRoute();
          directionsDisplay = new google.maps.DirectionsRenderer();
          var myOptions = {
              zoom:13,
              mapTypeId: google.maps.MapTypeId.ROADMAP
          }

          map = new google.maps.Map(document.getElementById("map"), myOptions);

          directionsDisplay.setMap(map);

          document.getElementById("submit").onclick = function() {
              calcRoute();
          }

      }

      function calcRoute() {
          var partenza = document.getElementById("partenza").value;
          var arrivo = document.getElementById("arrivo").value;
          var request = {
              origin:partenza,
              destination:arrivo,
              travelMode: google.maps.DirectionsTravelMode.DRIVING
          };
          directionsService.route(request, function(response, status) {
              if (status == google.maps.DirectionsStatus.OK) {
                  directionsDisplay.setDirections(response);
              }
          });
      }
      window.onload = initialize;
  </script>
</head>
<body>
<div>
  <strong>Partenza: </strong>
  <input type="text" id="partenza" value="<%= @post%>">
  <strong>Arrivo: </strong>
  <input type="text" id="arrivo" value="Via Zamboni - Bologna">
  <input id="submit" type="button" value="trova percorso sulla mappa">
</div>
<div id="map" style="width:500px; height: 500px"></div>
</body>
</html>

app/views/map/loc.html.erb
<html>
<head>
  <title>Geolocation</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <style>
      html, body, #map-canvas {
          height: 100%;
          margin: 0px;
          padding: 0px
      }
  </style>
  <!--
  Include the maps javascript with sensor=true because this code is using a
  sensor (a GPS locator) to determine the user's location.
  See: https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API
  -->
  <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDIAWj6dRK3iiTYm4q23Vbe-Ina6hSQfd0&sensor=true&language=it" type="text/javascript"></script>

  <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see a blank space instead of the map, this
      // is probably because you have denied permission for location sharing.

      var map;
      var pos;


      function handleNoGeolocation(errorFlag) {
          if (errorFlag) {
              var content = 'Error: The Geolocation service failed.';
              pos= "Catania ,Italia"

          } else {
              var content = 'Error: Your browser doesn\'t support geolocation.';
              pos= "Catania ,Italia"

          }
      }





      var directionDisplay;
      var directionsService = new google.maps.DirectionsService();

      function initialize() {

          calcRoute();
          directionsDisplay = new google.maps.DirectionsRenderer();
          var myOptions = {
// zoom:6, // non cambia nulla...
              mapTypeId: google.maps.MapTypeId.ROADMAP
          }

          map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);

          directionsDisplay.setMap(map);



      }

      function calcRoute() {

          var arrivo = "Catania , Italia"

// Try HTML5 geolocation
          if(navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(function(position) {

                          var request = {
                              origin: new google.maps.LatLng(position.coords.latitude,
                                      position.coords.longitude )
                              ,
                              destination:arrivo,
                              travelMode: google.maps.DirectionsTravelMode.DRIVING
                          };
                          directionsService.route(request, function(response, status) {
                              if (status == google.maps.DirectionsStatus.OK) {
                                  directionsDisplay.setDirections(response);
                              }
                          });


                      }
                      , function() {
                          handleNoGeolocation(true);
                      });
          } else {
// Browser doesn't support Geolocation
              handleNoGeolocation(false);
              var partenza = "Catania , Italia"
              var request = {
                  origin:partenza ,
                  destination:arrivo,
                  travelMode: google.maps.DirectionsTravelMode.DRIVING

              };
              directionsService.route(request, function(response, status) {
                  if (status == google.maps.DirectionsStatus.OK) {
                      directionsDisplay.setDirections(response);
                  }
              });
          }


      }
      window.onload = initialize;


  </script>
</head>
<body>

<div id="map-canvas" style="width:500px; height: 500px"></div>


</body>
</html>


<!--<#%= link_to 'New Post', new_post_path %>-->

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
    <div class="field">
      <%= f.label :Address %><br>
      <%= f.text_area :address %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDIAWj6dRK3iiTYm4q23Vbe-Ina6hSQfd0&sensor=false&language=it" type="text/javascript"></script>

app/views/posts/edit.html.erb
<div data-role="header">
  <h1>Editing Post</h1>
   <%= link_to 'Home', posts_path , 'data-icon' => 'home' , 'class' => 'ui-btn-left'  %>

</div>
<div data-role="content">
  <%= render 'form' %>
</div>

<!--
<#%= link_to 'Show', @post %> |
<#%= link_to 'Back', posts_path %>
-->


<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDIAWj6dRK3iiTYm4q23Vbe-Ina6hSQfd0&sensor=false&language=it" type="text/javascript"></script>


<script type="text/javascript">

    // function initialize(){


    //     var mapOptions = {
    //  center: new google.maps.LatLng(-34.397, 150.644),
    //     zoom: 8 ,
    //   mapTypeId: google.maps.MapTypeId.ROADMAP

    //        };
    //      var map= new google.maps.Map(document.getElementById("map-canvas"),
    //            mapOptions);


    //}

    //    google.maps.event.addDomListener(window,'load',initialize);

    function codeAddress(){

        var mapOptions = {
            mapTypeId: google.maps.MapTypeId.ROADMAP }

        var address = "<%= @post.address %>";
         var geocoder = new google.maps.Geocoder();

        geocoder.geocode({'address': address}, function(result,status){
            if(status == google.maps.GeocoderStatus.OK){
                map.setCenter(result[0].geometry.location);
                map.setZoom(14);
                var marker = new google.maps.Marker({
                    map: map,
                    position: result[0].geometry.location
                 });

            }else{

                alert("geocode was not successful for the following reason : " + status )

            }

        });

        var map= new google.maps.Map(document.getElementById("map-canvas2"),
                mapOptions);

    }





    google.maps.event.addDomListener(window,'load',codeAddress);

</script>
<div id="map-canvas2" style="width:100%; height: 400px"></div>
<!--<div id="map-canvas" style="width:100%; height: 400px"></div>-->

app/views/posts/index.html.erb
<div data-role="header">
<h1>Listing posts</h1>
  <%= link_to 'Add', new_post_path ,'data-icon' => 'plus' , 'class' => 'ui-btn-right' ,:target => '_parent'%>
</div>


    <div data-role="content">
      <ul data-role="listview">
    <% @posts.each do |post| %>
      <li>
         <%= link_to post.title , post ,:target => '_parent' %>
        <!-- <#%= post.body %>
       <#%= link_to 'Show', post %>  -->
         <%= link_to 'edit post', edit_post_path(post), 'data-icon'=> 'gear' ,:target => '_parent' %>
        <!-- <#%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        -->
      </li>
    <% end %>
      </ul>
    </div>





<!--<#%= link_to 'New Post', new_post_path %>-->

app/views/posts/new.html.erb
 <div data-role="header">
  <h1>New Post</h1>
  <%= link_to 'Home' , posts_path ,'data-icon' => 'home' , 'class' => 'ui-btn-left' , :target => '_parent' %>
</div>
<div data-role="content">
    <%= render 'form' %>


</div>
<!--
<#%= link_to 'Back', posts_path %>
-->

app/views/posts/show.html.erb
<!-- <p id="notice"><#%= notice %></p>

<p>
  <strong>Title:</strong>
  <#%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <#%= @post.body %>
</p>

<#%= link_to 'Edit', edit_post_path(@post) %> |
<#%= link_to 'Back', posts_path %>
-->

<div data-role="header">
  <h1><%= @post.title %></h1>
  <%= link_to 'Home', posts_path , 'data-icon' => 'home' , 'class' => 'ui-btn-left' , :target => '_parent'%>
</div>



<div data-role="content">

    <%= form_for (@post) do |f| %>
      <div class="field">
        <strong><%= f.label :Body %></strong>
        <%= f.text_field :body, :readonly => true %>
      </div>
      <br/>

          <div class="field">
            <strong><%= f.label :Address %></strong>
            <%= f.text_field :address, :readonly => true %>
          </div>

  <% end %>

</div>


<html>
<head>
  <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDIAWj6dRK3iiTYm4q23Vbe-Ina6hSQfd0&sensor=false&language=it" type="text/javascript"></script>
  <script type="text/javascript">
      var directionDisplay;
      var directionsService = new google.maps.DirectionsService();
      var map;

      function initialize() {

          calcRoute();
          directionsDisplay = new google.maps.DirectionsRenderer();
          var myOptions = {
              // zoom:6, // non cambia nulla...
              mapTypeId: google.maps.MapTypeId.ROADMAP
          }

          map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);

          directionsDisplay.setMap(map);



      }

      function calcRoute() {
          var geocoder = new google.maps.Geocoder();
          var address = "<%= @post.address %>";

          geocoder.geocode({'address': address}, function(result,status){
              if(status == google.maps.GeocoderStatus.OK){

                  var partenza =address;


              }else{
                  var partenza = "Catania , Italia"
                  alert("geocode was not successful for the following reason : " + status )

              }
              var arrivo = "Catania , Italia"

              var request = {
                  origin:partenza,
                  destination:arrivo,
                  travelMode: google.maps.DirectionsTravelMode.DRIVING
              };

              directionsService.route(request, function(response, status) {
                  if (status == google.maps.DirectionsStatus.OK) {
                      directionsDisplay.setDirections(response);
                  }
              });
          });
      }
      window.onload = initialize;
  </script>
</head>
<body>

<div id="map-canvas" style="width:500px; height: 500px"></div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :encryptedpassword %><br>
    <%= f.text_field :encryptedpassword %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.number_field :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Encryptedpassword</th>
      <th>Salt</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.encryptedpassword %></td>
        <td><%= user.salt %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Encryptedpassword:</strong>
  <%= @user.encryptedpassword %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>


<%= gravatar_for @user %>